name: exitnode

services:
  ts-exitnode:
    image: tailscale/tailscale:latest
    container_name: ts-exitnode
    hostname: acainode
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}?ephemeral=false
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      # - TS_SERVE_CONFIG=/config/ts-exitnode.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${APP_CONFIG_DIR}/ts-exitnode/state:/var/lib/tailscale
      # - ./../configs:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart: unless-stopped
    networks:
      - exitnode

networks:
  exitnode:
    name: exitnode
