name: hotflix

services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=13000
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_SERVER_URL}
    volumes:
      - ${APP_CONFIG_DIR}/hotflix/jellyfin/config:/config
      - ${HOTFLIX_DATA_DIR}/shows/media:/media/shows:ro
      - ${HOTFLIX_DATA_DIR}/movies/media:/media/movies:ro
    ports:
      - 8096:8096
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart: unless-stopped

  # Servarr Apps (Tailscale TSDProxy)

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13000
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/hotflix/radarr:/config
      - ${HOTFLIX_DATA_DIR}/movies:/data/movies
    ports:
      - 7878:7878
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "movies"
      tsdproxy.ephemeral: "false"
    networks:
      - tailproxy
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13000
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/hotflix/sonarr:/config
      - ${HOTFLIX_DATA_DIR}/shows:/data/shows
    ports:
      - 8989:8989
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "shows"
      tsdproxy.ephemeral: "false"
    networks:
      - tailproxy
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13000
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${APP_CONFIG_DIR}/hotflix/qbittorrent:/config
      - ${HOTFLIX_DATA_DIR}/shows/torrents:/data/shows/torrents
      - ${HOTFLIX_DATA_DIR}/movies/torrents:/data/movies/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "torrent"
      tsdproxy.container_port: 8080
      tsdproxy.ephemeral: "false"
    networks:
      - tailproxy
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=13000
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CONFIG_DIR}/hotflix/prowlarr:/config
    ports:
      - 9696:9696
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "prowlarr"
      tsdproxy.ephemeral: "false"
    networks:
      - tailproxy
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - 8191:8191
    networks:
      - tailproxy
    restart: unless-stopped

networks:
  tailcar:
    name: tailcar
  tailproxy:
    name: tailproxy
    external: true
