name: museek

services:
  museek:
    image: ghcr.io/6amedev/museek:main
    container_name: museek
    environment:
      - ENV=production
      - MEMCACHE_ADDR=mucache:11211
      - APP_URL=http://museek.home.lab
      - SEEKER_HOST=http://seeker:8000
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    volumes:
      - ${APP_CONFIG_DIR}/museek:/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "museek"
      tsdproxy.ephemeral: "false"
      com.centurylinklabs.watchtower.enable: "false"
    ports:
      - "8020:8090"
    networks:
      - tailproxy
    restart: unless-stopped

  mucache:
    image: memcached:1.6-alpine
    container_name: mucache
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    ports:
      - "11211:11211"
    networks:
      - tailproxy
    restart: unless-stopped

  seeker:
    image: ghcr.io/6amedev/seeker:main
    container_name: seeker
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    ports:
      - "8001:8000"
    networks:
      - tailproxy
    restart: unless-stopped

networks:
  tailproxy:
    name: tailproxy
    external: true
