name: museek

services:
  museek:
    image: ghcr.io/6amedev/museek:main
    container_name: museek
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ${APP_CONFIG_DIR}/museek:/museek_data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "museek"
      tsdproxy.ephemeral: "false"
      com.centurylinklabs.watchtower.enable: "false"
    ports:
      - "8020:8090"
    networks:
      - tailproxy
    restart: unless-stopped

networks:
  tailproxy:
    name: tailproxy
    external: true
