name: museek

services:
  museek:
    image: ghcr.io/6amedev/museek:main
    container_name: museek
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - SAVED_TRACKS_IMAGE_URL=${SAVED_TRACKS_IMAGE_URL}
      - AIOTUBE_HOST=http://aiotube:8000
    volumes:
      - ${APP_CONFIG_DIR}/museek:/museek_data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "museek"
      tsdproxy.ephemeral: "false"
      com.centurylinklabs.watchtower.enable: "false"
    ports:
      - "8020:8090"
    networks:
      - tailproxy
    restart: unless-stopped

  aiotube:
    image: ghcr.io/6amedev/aiotube:videos-metadata
    container_name: aiotube
    ports:
      - "8000:8000"
    networks:
      - tailproxy
    restart: unless-stopped

networks:
  tailproxy:
    name: tailproxy
    external: true
